/**
 * Types for the stock screener — a research surface for stocks you may buy,
 * seeded from an index's constituents or individually-added tickers.
 */

/** One constituent of an index, as generated by scripts/fetch-constituents.mjs. */
export interface IndexConstituent {
    /** Yahoo symbol, e.g. "8306.T". */
    symbol: string;
    /** Native exchange code, e.g. "8306" or "285A". */
    code: string;
    name: string;
    sector: string | null;
}

/** A user-set price alert: fire when the live price crosses `target`. */
export interface PriceAlert {
    target: number;
    direction: 'above' | 'below';
}

/** Shape of each src/data/indices/<key>.json file. */
export interface IndexConstituentsFile {
    index: string;
    asOf: string | null;
    source: string;
    fetchedAt: string;
    count: number;
    constituents: IndexConstituent[];
}

/**
 * Normalized per-stock fundamentals served by /api/screener/quote (Phase 2).
 * Sourced from Yahoo's authenticated quoteSummary; any field may be null when
 * Yahoo omits it. `forwardPriceToBook` is intentionally absent — Yahoo exposes
 * no forward book value.
 */
export interface StockFundamentals {
    symbol: string;
    name: string | null;
    price: number | null;
    currency: string | null;
    trailingPE: number | null;
    forwardPE: number | null;
    /** Fractional, e.g. 0.034 = 3.4%. */
    dividendYield: number | null;
    priceToBook: number | null;
    marketCap: number | null;
    sector: string | null;
}
